# Default values for tracker_simulator.
global:
  appName: "tracker-simulator"
  secrets:
    googleMapsApiKey: "<YOUR_GOOGLE_API_KEY>"

  jaeger:
    host: &jaegerHost "<YOUR_INFRA_HOST_IP_OR_DNS>"
    port: 4317

  redis:
    host: &redisHost "<YOUR_INFRA_HOST_IP_OR_DNS>"
    port: 6379
    streamKey: "latency:metrics:stream"

  mqtt:
    host: &mqttHost "<YOUR_INFRA_HOST_IP_OR_DNS>"
    port: 1883
    quicPort: 14567

  envoy:
    host: &envoyHost "<YOUR_LOAD_BALANCER_IP_OR_DNS>"
    trackerServerPort: &trackerServerPort 8088
    trackerServerGrpcPort: &trackerServerGrpcPort 9003
    trackerClientPort: &trackerClientPort 8089
    trackerAnalyticsPort: &trackerAnalyticsPort 5050
    communicationsAppPort: &communicationsAppPort 8080

trackerserver:
  trackerServer:
    trackerClientHost: *envoyHost
    trackerClientPort: *trackerClientPort
    port: 8088
    grpcServerPort: 9003
    maxConnectionsPerHost: 30
    image:
      repository: docker.io/jhonnyvennom/tracker-jar
      tag: "1.7.0"
      arch: amd64
    replicas: 1
    resources:
      requests: { memory: "256Mi", cpu: "100m" }
      limits:   { memory: "256Mi", cpu: "100m" }
    nodeSelector: []

trackerclient:
  trackerClient:
    host: *envoyHost
    port: 8089
    grpcPort: 9004
    grpcServerPort: *trackerServerGrpcPort
    trackerServerHost: *envoyHost
    trackerServerPort: *trackerServerPort
    image:
      repository: docker.io/jhonnyvennom/tracker-client
      tag: "2.2.0"
      arch: amd64
    replicas: 1
    resources:
      requests: { memory: "256Mi", cpu: "100m" }
      limits:   { memory: "256Mi", cpu: "100m" }
    nodeSelector: []

communicationsapp:
  communicationsApp:
    host: *envoyHost
    port: 80
    serverPort: *trackerServerPort
    servicePort: 8080    
    trackerApp:
      port: *trackerServerPort
    trackerClientApp:
      port: *trackerClientPort
    trackerAnalyticsApp:
      port: *trackerAnalyticsPort
    mqttWsUrl: "ws://{{ .Values.global.mqtt.host }}:8090/mqtt"
    image:
      repository: docker.io/jhonnyvennom/communications_app
      tag: "1.6.1"
      arch: amd64
    replicas: 1
    resources:
      requests: { memory: "256Mi", cpu: "100m" }
      limits:   { memory: "256Mi", cpu: "100m" }
    nodeSelector: []
      
trackeranalytics:
  trackerAnalytics:
    port: 5050
    image:
      repository: docker.io/jhonnyvennom/tracker-analytics
      tag: "1.2.1"
      arch: amd64
    replicas: 1
    resources:
      requests: { memory: "256Mi", cpu: "100m" }
      limits:   { memory: "256Mi", cpu: "100m" }
    nodeSelector: []